home/urls.py
from django.urls import path
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.contrib import admin

from .views import IndexView,AboutView,PortfolioView,PortfolioDetailView,BlogView,BlogDetailView,SearchView,ContactView
from .models import Blog

info_dict = {
    'queryset': Blog.published.all(),
    'date_field': 'created',
}

app_name="home"

admin.site.site_title = 'Portfolio'
admin.site.site_header = 'My portfolio Website'    
admin.site.index_title = 'Features Area'

urlpatterns = [
    path('',IndexView.as_view(),name='index'),
    path('about/',AboutView.as_view(),name='about'),
    path('portfolio/',PortfolioView.as_view(),name='project'),
    path('portfolio/<slug:slug>/',PortfolioDetailView.as_view(),name='project_detail'),
    path('blogs/',BlogView.as_view(),name='blogs'),
    path('tags/<slug:tag_slug>/',BlogView.as_view(),name='tags'),
    path('categories/<slug:categories>/',BlogView.as_view(),name='categories'),
    path('blogs/<slug:slug>/',BlogDetailView.as_view(),name='blog_detail'),
    path('search/',SearchView.as_view(),name='search'),
    path('contact/',ContactView.as_view(),name='contact'),
    path('sitemap.xml', sitemap,
         {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}},
         name='django.contrib.sitemaps.views.sitemap'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone

from taggit.managers import TaggableManager
from taggit.models import TagBase, GenericTaggedItemBase

from ckeditor_uploader.fields import RichTextUploadingField


############## Project ##################

class ProjectTechnology(TagBase):
    class Meta:
        verbose_name = _("Technology")
        verbose_name_plural = _("Technologies")


class TaggedTechnologies(GenericTaggedItemBase):
    tag = models.ForeignKey(ProjectTechnology,on_delete=models.CASCADE,
                            related_name="%(app_label)s_%(class)s_items")


class Project(models.Model):

    Project_Type_CHOICES = [
    ('Personal','Personal'),
    ('Client','Client')
    ]

    title = models.CharField(max_length=254)
    slug = models.SlugField(max_length=300,unique=True)
    thumbnail = models.ImageField(upload_to="project/thumbnail")
    github = models.URLField(null=True,blank=True)
    tag = models.CharField(max_length=10,choices=Project_Type_CHOICES)
    preview = models.URLField(null=True,blank=True)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    technologies = TaggableManager(through=TaggedTechnologies,verbose_name='Technologies')

    def get_absolute_url(self):
        return reverse("home:project_detail",kwargs={'slug':self.slug})

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title


class ProjectImage(models.Model):
    project = models.ForeignKey(Project, default=None, related_name="images", on_delete=models.CASCADE)
    images = models.FileField(upload_to = 'project/images/')
 
    def __str__(self):
        return self.project.title


############## Blogs ##################


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')


class Categories(models.Model):
    title = models.CharField(max_length=254)
    slug = models.SlugField(max_length=250,unique=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Blog(models.Model):

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    body = RichTextUploadingField(external_plugin_resources=[(
        'youtube',
        '/static/js/ckeditor/youtube/',
        'plugin.js',
    )],)
    thumbnail = models.ImageField(upload_to="blogs/thumbnail")
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    categories = models.ManyToManyField(Categories)
    tags = TaggableManager()
    objects = models.Manager() 
    published = PublishedManager()

    class Meta:
        ordering = ('-created',)
    
    def __str__(self):
     return self.title

    def get_absolute_url(self):
        return reverse("home:blog_detail",kwargs={'slug':self.slug})


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
   
    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.blog}'

home/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Your Name'}),label='')
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'comment-gap','rows':'5','placeholder':'Your Comment'}),label='')
    
    class Meta:
        model = Comment
        fields = ('name', 'body')

home/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib import messages
from django.contrib.postgres.search import SearchVector
from django.core.mail import send_mail
from django.db.models import Count
from django.urls import reverse
from django.views.generic import TemplateView,ListView,DetailView,View
from django.conf import settings

from .models import Project,ProjectImage,Blog,Comment,Categories
from .forms import CommentForm

from taggit.models import Tag

class IndexView(TemplateView):
    template_name = "index.html"

class AboutView(TemplateView):
    template_name = "about.html"

class PortfolioView(ListView):
    model = Project
    template_name = 'portfolio.html'
    context_object_name = 'projects'

class PortfolioDetailView(DetailView):
    model = Project
    template_name = 'portfolio-detail.html'
    context_object_name = 'project'


class BlogView(ListView):
    model = Blog
    paginate_by = 8
    template_name = 'blogs.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        queryset = Blog.published.all()
        if self.kwargs.get('tag_slug'):
            tag = get_object_or_404(Tag,slug=self.kwargs.get('tag_slug'))
            queryset = queryset.filter(tags__in=[tag])
            context['tag'] = tag.name
        
        if self.kwargs.get('categories'):
            categories = get_object_or_404(Categories,slug=self.kwargs.get('categories'))
            queryset = queryset.filter(categories__in=[categories])
            context['categories'] = categories.title

        context['blogs'] = queryset
        
        return context



class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog-detail.html'

    def get_object(self):
        obj = get_object_or_404(Blog,slug=self.kwargs.get('slug'),status='published')
        return obj

    def comment_posted(self,boolean=False):
        return boolean

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        blog = self.get_object()

        tags_list = blog.tags.values_list('id',flat=True)
        similar_blogs = Blog.published.filter(tags__in=tags_list).exclude(id=blog.id)
        similar_blogs = similar_blogs.annotate(tags_num=Count('tags')).order_by('-tags','-publish')[:2]

        comments = blog.comments.filter(active=True).order_by('-created')

        context['blog'] = blog
        context['similars'] = similar_blogs
        context['form'] = CommentForm()
        context['comments'] = comments
        return context

    def post(self,request,**kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            blog = self.get_object()
            form.instance.blog = blog
            form.save() 
            messages.success(request, 'Your comment has been added')
            return redirect(reverse("home:blog_detail", kwargs={'slug': blog.slug}))


class SearchView(View):
    
    def get(self,request):
        query = None
        results = []
        if 'q' in request.GET:
            query = request.GET.get('q')
            results = Blog.published.annotate(search=SearchVector('title','body')).filter(search=query)
        return render(request,'search.html',{'query':query,'results':results})

class ContactView(TemplateView):
    template_name = "contact.html"
    def post(self,request,**kwargs):
            email = self.request.POST['email']
            name = self.request.POST['name']
            message = self.request.POST['message']
            send_mail(f'{name} sent mail through lamdiv',
                      f'{message}\n\nname: {name} \nemail: {email}',
                      settings.EMAIL_HOST_USER,
                      ['your email'],fail_silently=False)
            messages.success(request, 'Your message has been sent')
            return redirect(reverse("home:contact"))

home/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
    <link rel="stylesheet" href="{%static 'css/media.css'%}">
    <script src="https://kit.fontawesome.com/7c8f6ae518.js" crossorigin="anonymous"></script>
    <title>{%block title%}{%endblock%}</title>
</head>
<body>

    {%block content%}
    {%endblock%}
</body>
</html>

home/templates/blog-detail.html
<!DOCTYPE html>
{%load static%}
{% load blogs_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{{blog.body|safe|truncatechars:150}}"/>
    <meta property="og:title" content="{{blog.title.title}}">
    <meta property="og:image" content="{{blog.thumbnail.url}}">
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
    <link rel="stylesheet" href="{%static 'css/media.css'%}">
    <script src="https://kit.fontawesome.com/7c8f6ae518.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/styles/default.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <title>{{blog.title.title}}</title>
</head>
<body>
    <header>
        {%include "./navbar.html"%}
        <section class="blogs">
            <div class="blogs-elements ">
                  <div class="blog-content">
                    <div class="blog-header">
                        {%for tag in blog.tags.all%}
                        <div class="tags2">{{tag}}</div>
                        {%endfor%}
                        <i class="fas fa-calendar-day"></i><h5>&nbsp;{{blog.publish|date:'M j Y'}}</h5>&nbsp;&nbsp;&nbsp;
                        <i class="fas fa-comment"></i>&nbsp;{{comments.count}}
                    </div>
                    <h1 class="extra-height-4" style="color: white;">{{blog.title.title}}</h1>
                    <div class="thumbnail"><img src="{{blog.thumbnail.url}}" alt="{{blog.title}}"></div>
                    <div class="paragraph">
                        {{blog.body|safe}}
                    </div>
                    <div class="footer">
                        <div><i class="fas fa-pen-alt color-me"></i> &nbsp;&nbsp;{{ blog.author.get_full_name|default:blog.author.username }}</div>
                        <div>Share &nbsp;&nbsp;
                            <i class="fab fa-facebook"></i>&nbsp;&nbsp;
                            <i class="fab fa-twitter"></i>
                         </div>
                    </div>
                    <div class="similar-posts ">
                        {%if similars%}
                        <h4 class="center-align">Similar Posts</h4>
                        {%endif%}
                        <div class="similar-merge">
                            {%if similars%}

                            {%for similar in similars%}

                            {% if forloop.first and forloop.first != forloop.last%}
                            <div class="similar">
                                    <a href = "{{similar.get_absolute_url}}" class="arrow">&#10094;</a>
                                    <img src="{{similar.thumbnail.url}}">
                                    <p>{{similar.title.title}}</p>     
                            </div>
                            {%endif%}

                            {% if forloop.last%}
                            <div class="similar">
                                    <p style="text-align: right;">{{similar.title.title}}</p> 
                                    <img  class="gap" src="{{similar.thumbnail.url}}"> 
                                    <a href = "{{similar.get_absolute_url}}" class="arrow">&#10095;</a>
                            </div>
                            {%endif%}

                            {%endfor%}
                            {%endif%}
                        </div> 
                </div>
                   
                    <div class="comment">
                        {%with comments.count as total_comments%}
                        <h3 class="center-align">{{total_comments}} &nbsp; Comment{{total_comments|pluralize}}</h3>
                        {%endwith%}
                        <div class="comments">
                            {% for comment in comments%}
                            <div class="reply">
                                <img src="{% static 'assets/pic2.jpg'%}">
                                <div class="info">
                                    <h5>{{comment.name.title}}</h5>
                                    <p class="time"><i class="fas fa-clock"></i> &nbsp; {{comment.created|timesince}}</p>
                                    <p class="comment-text">{{comment.body}}</p>
                                </div>
                            </div>
                            {%empty%}
                            <p class="just-no align-me">No comments yet</p> 
                            {%endfor%}

                            
                        </div>
                    </div>
                    {% if messages %}
                    <ul class="messages align-me">
                        {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}><h3>{{message}}</h3></li>
                        {% endfor %}
                    </ul>
                    {%else%}
                    <div class="add">
                        <h3 class="center-align">Add a comment</h3>
                        <form class="align-me" method="POST" action=".">
                            {%csrf_token%}
                            <div class="form comment-gap">
                                {{form.as_p}}
                            </div>
                            <input type="submit" value="Comment" class="btn-orange">
                        </form>
                    </div>
                    {% endif %}

                  </div>
                  <div class="blogs-sidebar">
                    <form method="GET" action="/search">
                        <div class="search extra-height">
                            <div class="search-bar" >
                            <input name="q" type="text" placeholder="search">
                            <button class="search-icon"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                    </form>
                    <div class="extra-height">
                        <h4 class="extra-height-3">Top Posts</h4>
                        <div class="top-posts">
                            {% top_posts as posts %}
                            {%for post in posts %}
                            <div class="post">
                                <a href="{{post.get_absolute_url}}"><img class="post-img" src="{{post.thumbnail.url}}"></a>
                                 <a href="{{post.get_absolute_url}}"><p class="small-p">{{post.title.title}}</p></a>
                                <div class="calender">
                                    <i class="fas fa-calendar-day"></i>
                                    <h5>{{post.publish|date:'M j Y'}}</h5>
                                </div>
                            </div>
                            {%empty%}
                            <p class="just-no align-me" style="margin-bottom: 30px;">No Top Post</p> 
                            {%endfor%}
                            
                        </div>
                    </div>
                    <div class="extra-height">
                        <h4 class="extra-height-3">Categories</h4>
                        <div class="categories">
                            {% categories as cats %}
                            {% for cat in cats %}
                            <div class="category"><a href="{% url 'home:categories' cat.categories__slug %}"><p class="small-p-1">{{cat.categories__title}}</p></a><p class="small-p-1">{{cat.categories__title__count}}</p></div>
                            {%empty%}
                            <p class="just-no align-me" style="margin-bottom: 30px;">No Category</p> 
                            {%endfor%}
                        </div>
                    </div>
                    <div class="extra-height">
                        <h4 class="extra-height-3">Tags Cloud</h4>
                        
                        {%tags as all_tags%}
                        <div class="tags" {%if not all_tags%} style="justify-content:center;" {%endif%}>
                        {%for tag in all_tags%}
                        <div class="tag"><a href="{% url 'home:tags' tag.tags__slug %}">{{tag.tags__name}}</a></div>
                        {%empty%}
                            <p class="just-no align-me" style="margin-bottom: 30px;" >No Tags</p> 
                        {%endfor%}
                    </div>
                </div>
                    </div>
            </div>
            
        </section>
    </header>
    
</body>
</html>

home/templates/blogs.html
<!DOCTYPE html>
{%load static%}
{%load blogs_tags%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
    <link rel="stylesheet" href="{%static 'css/media.css'%}">
    <script src="https://kit.fontawesome.com/7c8f6ae518.js" crossorigin="anonymous"></script>
    <title>My portfolio | Blogs</title>
</head>
<body>
    <header>
        {%include "./navbar.html"%}
        <section class="blogs">
            {%if tag%}
            <h3 style="display: inline-block;" 
            class="extra-height center-align">

            Blogs tagged with
            
            <h2
             style="margin-left:15px;display: inline-block;"
             >
             "{{tag}}"</h2></h3>
             
             {%elif categories%} <h2 class="extra-height center-align">{{categories.title}}</h2>
            {%else%}
             <h2 class="extra-height center-align"> My blogs</h2>{%endif%}

            <div class="blogs-elements">
                  <div class="blog-main">
                    <div class="pagination-aligner">
                        <div class="blog-arrange" style="{%if not blogs%} justify-content:center; {%endif%}">

                        {%for blog in blogs%}
                        <div class="blog">
                            <img src="{{blog.thumbnail.url}}">
                            <div class="over-img">
                                
                                <div class="tags">
                                    {%for tags in blog.tags.all%}
                                    <div class="tags3">{{tags}}</div>
                                    {%endfor%}
                                </div>
                            </div>
                            <div class="blog-title">
                                <h4 class="title">{{blog.title.title}}</h4>
                                <!-- <div><i class="fas fa-comment"></i>0</div> -->
                            </div>
                            <div class="description">
                                {{blog.body|safe|truncatewords:30}}
                            </div>
                            <button class="read-more"><a href="{{blog.get_absolute_url}}">read more ></a></button>
                        </div>
                        {%empty%}
                            <p class="just-no align-me" style="margin-bottom: 30px;">No Post yet</p> 

                        {%endfor%}
                        </div>
                        {%if blogs%}
                        <div class="pagination">
                            {% if page_obj.has_previous %}
                                <div><a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></div>
                                <div><a href="?page={{ page_obj.previous_page_number }}">&#10094;</a></div>
                            {% endif %}
                            
                            <div class="active-1">{{page_obj.number}}</div>
                            {% if page_obj.has_next %}
                            <div><a href="?page={{page_obj.next_page_number}}">{{page_obj.next_page_number}}</a></div>
                            <div><a href="?page={{page_obj.next_page_number}}">&#10095;</a></div>
                            {% endif %}
                        
                        </div> 
                        {%endif%}
                    </div>
                  </div>


                  <div class="blogs-sidebar">
                    <form method="GET" action="/search">
                        <div class="search extra-height">
                            <div class="search-bar" >
                            <input name="q" type="text" placeholder="search">
                            <button class="search-icon"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                    </form>
                    <div class="extra-height">
                        <h4 class="extra-height-3">Top Posts</h4>
                        <div class="top-posts">
                            {% top_posts as posts %}
                            {%for post in posts %}
                            <div class="post">
                                <a href="{{post.get_absolute_url}}"><img class="post-img" src="{{post.thumbnail.url}}"></a>
                                 <a href="{{post.get_absolute_url}}"><p class="small-p">{{post.title.title}}</p></a>
                                <div class="calender">
                                    <i class="fas fa-calendar-day"></i>
                                    <h5>{{post.publish|date:'M j Y'}}</h5>
                                </div>
                            </div>
                            {%empty%}
                            <p class="just-no align-me" style="margin-bottom: 30px;">No Top Post</p> 
                            {%endfor%}
                            
                        </div>
                    </div>
                    <div class="extra-height">
                        <h4 class="extra-height-3">Categories</h4>
                        <div class="categories">
                            {% categories as cats %}
                            {% for cat in cats %}
                            <div class="category"><a href="{% url 'home:categories' cat.categories__slug %}"><p class="small-p-1">{{cat.categories__title}}</p></a><p class="small-p-1">{{cat.categories__title__count}}</p></div>
                            {%empty%}
                            <p class="just-no align-me" style="margin-bottom: 30px;">No Category</p> 
                            {%endfor%}
                        </div>
                    </div>
                    <div class="extra-height">
                        <h4 class="extra-height-3">Tags Cloud</h4>
                        {%tags as all_tags%}
                    <div class="tags" {%if not all_tags%} style="justify-content:center;" {%endif%}>
                        
                        {%for tag in all_tags%}
                        <div class="tag"><a href="{% url 'home:tags' tag.tags__slug %}">{{tag.tags__name}}</a></div>
                        {%empty%}
                            <p class="just-no align-me" style="margin-bottom: 30px;" >No Tags</p> 
                        {%endfor%}
                    </div>
                </div>
                    </div>
            </div>
            
        </section>
    </header>
    
</body>
</html>

home/templates/index.html
{%extends "./base.html"%}
{%load static%}
{%block title%}My Portfolio{%endblock%}
{%block content%}
    <header>
       {%include "./navbar.html"%}
        <section class="home">    
            <img src="{%static 'assets/circular-diwash.png'%}" class="home-img-responsive">
            <img src="{%static 'assets/diwash.png'%}" class="home-img">
            <div class="home-info">
                <p>HEY! I AM</p>
                <h1>Diwash Lamichhane</h1>
                <h3>I'm a Web Developer</h3>
                <button class="btn-orange margin-btn"><a href="/about">About me</a></button>
            </div>
        </section>
    </header>
{%endblock%}

home/templates/search.html
{%extends "./base.html"%}
{%load static%}
{%block content%}

    <header>
        {%include "./navbar.html"%}
        <section class="blogs">
            <h3 style="display: inline-block;" class="extra-height center-align">Search Results for <h2 style="margin-left:15px;display: inline-block;">"{{query}}"</h2></h3>
            <div class="blogs-elements">
                  <div class="blog-main">
                    <div class="pagination-aligner">
                        <div class="blog-arrange" style="{%if not results%} justify-content:center; {%endif%}">

                        {%for blog in results%}
                        <div class="blog">
                            <img src="{{blog.thumbnail.url}}">
                            <div class="over-img">
                                
                                <div class="tags">
                                    {%for tags in blog.tags.all%}
                                    <div class="tags3">{{tags}}</div>
                                    {%endfor%}
                                </div>
                            </div>
                            <div class="blog-title">
                                <h4 class="title">{{blog.title.title}}</h4>
                                <div><i class="fas fa-comment"></i>27</div>
                            </div>
                            <div class="description">
                                {{blog.body|safe|truncatewords:30}}
                            </div>
                            <button class="read-more"><a href="{{blog.get_absolute_url}}">read more ></a></button>
                        </div>
                        {%empty%}
                            <p class="just-no align-me" style="margin-bottom: 30px;">No Results Found</p> 
                        {%endfor%}
                        </div>
                    </div>
                  </div>


                  <div class="blogs-sidebar">
                    <form method="GET" action="/search">
                        <div class="search extra-height">
                            <div class="search-bar" >
                            <input name="q" type="text" placeholder="search">
                            <button class="search-icon"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                    </form>
                    <div class="extra-height">
                        <h4 class="extra-height-3">Top Posts</h4>
                        <div class="top-posts">
                            {% top_posts as posts %}
                            {%for post in posts %}
                            <div class="post">
                                <a href="{{post.get_absolute_url}}"><img class="post-img" src="{{post.thumbnail.url}}"></a>
                                 <a href="{{post.get_absolute_url}}"><p class="small-p">{{post.title.title}}</p></a>
                                <div class="calender">
                                    <i class="fas fa-calendar-day"></i>
                                    <h5>{{post.publish|date:'M j Y'}}</h5>
                                </div>
                            </div>
                            {%empty%}
                            <p class="just-no align-me" style="margin-bottom: 30px;">No Top Post</p> 
                            {%endfor%}
                            
                        </div>
                    </div>
                    <div class="extra-height">
                        <h4 class="extra-height-3">Categories</h4>
                        <div class="categories">
                            {% categories as cats %}
                            {% for cat in cats %}
                            <div class="category"><a href="{% url 'home:categories' cat.categories__slug %}"><p class="small-p-1">{{cat.categories__title}}</p></a><p class="small-p-1">{{cat.categories__title__count}}</p></div>
                            {%empty%}
                            <p class="just-no align-me" style="margin-bottom: 30px;">No Category</p> 
                            {%endfor%}
                        </div>
                    </div>
                    <div class="extra-height">
                        <h4 class="extra-height-3">Tags Cloud</h4>

                        {%for tag in all_tags%}
                    <div class="tags"{%if not all_tags%} style="justify-content:center;" {%endif%}>
                       
                        <div class="tag"><a href="{% url 'home:tags' tag.tags__slug %}">{{tag.tags__name}}</a></div>
                        {%empty%}
                        <p class="just-no align-me" style="margin-bottom: 30px;" >No Tags</p> 
                        {%endfor%}
                    </div>
                </div>
                    </div>
            </div>
            
        </section>
    </header>
{%endblock%}